
import requests
import json
import os
import sys
sys.path.append('/opt/Way To Future考试管理系统/Student_grade_system')
from wtf_app_simple import app, db, Student, ExamTemplate, ExamRegistration, ReportCard, Question, Score

# Setup context
ctx = app.app_context()
ctx.push()

def verify_ai_comment_flow():
    print("=== Verifying AI Comment Flow ===")
    
    # 1. Pick a test case (G6 Longman English)
    # Use a student known to exist or create a dummy one
    student_id = 1  # Assuming student 1 exists
    template_id = 118 # G6 Longman English
    
    student = Student.query.get(student_id)
    template = ExamTemplate.query.get(template_id)
    
    if not student or not template:
        print(f"Error: Student {student_id} or Template {template_id} not found.")
        return

    print(f"Testing with Student: {student.name} (ID: {student.id})")
    print(f"Testing with Template: {template.name} (ID: {template.id})")

    # Ensure registration exists
    reg = ExamRegistration.query.filter_by(student_id=student_id, exam_template_id=template_id).first()
    if not reg:
        print("Creating registration...")
        reg = ExamRegistration(
            student_id=student_id, 
            exam_template_id=template_id, 
            exam_session_id=template.exam_session_id,
            attendance_status='present'
        )
        db.session.add(reg)
        db.session.commit()
    
    # Ensure ReportCard exists
    report_card = ReportCard.query.filter_by(registration_id=reg.id).first()
    if not report_card:
        print("Creating report card...")
        report_card = ReportCard(registration_id=reg.id)
        db.session.add(report_card)
        db.session.commit()
        
    # 2. Simulate saving AI comment via DB directly (mimicking API behavior)
    test_comment = "This is a TEST AI COMMENT generated by verification script."
    print(f"Saving comment: '{test_comment}'")
    
    report_card.ai_comment = test_comment
    db.session.commit()
    
    # Verify DB save
    rc_check = ReportCard.query.filter_by(registration_id=reg.id).first()
    if rc_check.ai_comment == test_comment:
        print("PASS: Comment saved to database successfully.")
    else:
        print(f"FAIL: Comment not saved. Found: {rc_check.ai_comment}")
        return

    # 3. Verify PDF Generation logic
    # We can't easily capture the PDF output content without parsing PDF, 
    # but we can call the generation function and ensure no errors, 
    # and maybe inspect the variable if we could instrument it, but for now just run it.
    
    print("Generating PDF...")
    try:
        from wtf_app_simple import generate_report_card_pdf
        # generate_report_card_pdf(student_id, exam_session_id, template_id)
        pdf_bytes = generate_report_card_pdf(student_id, template.exam_session_id, template_id)
        
        # The function returns BytesIO, not bytes directly in some versions, or bytes?
        # Let's check type.
        if hasattr(pdf_bytes, 'getvalue'):
             pdf_bytes = pdf_bytes.getvalue()
        
        if pdf_bytes and len(pdf_bytes) > 0:
            output_filename = f"verify_ai_comment_{student_id}_{template_id}.pdf"
            with open(output_filename, "wb") as f:
                f.write(pdf_bytes)
            print(f"PASS: PDF generated successfully ({len(pdf_bytes)} bytes). Saved to {output_filename}")
            print("Please manually check the PDF to confirm the comment appears.")
        else:
            print("FAIL: PDF generation returned empty bytes.")
            
    except Exception as e:
        print(f"FAIL: PDF generation raised exception: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    verify_ai_comment_flow()
